-- Channel Analyst, Step 1: database tables (docs/analyst-build-spec.md, section 4).
-- Everything lives in the "content" schema. The public schema and
-- public.content_registry (ManyChat / ig-attribution) are not touched.

create schema if not exists content;

-- ---------------------------------------------------------------------------
-- account_stages: the account's business stages (section 8). Editable config.
-- ---------------------------------------------------------------------------
create table content.account_stages (
    id            integer generated by default as identity primary key,
    name          text not null unique,
    start_date    date not null,
    end_date      date,                       -- null = open-ended (current stage)
    goal_metrics  text not null,
    notes         text,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    constraint account_stages_dates_chk check (end_date is null or end_date >= start_date)
);

-- ---------------------------------------------------------------------------
-- business_events: launches and other dated events (section 8).
-- ---------------------------------------------------------------------------
create table content.business_events (
    id              integer generated by default as identity primary key,
    event_date      date not null,             -- first day of the (earliest) month when approximate
    event_name      text not null unique,
    is_approximate  boolean not null default false,
    date_label      text,                       -- the date as originally written, e.g. 'Feb/Mar 2024'
    notes           text,
    created_at      timestamptz not null default now()
);

create index business_events_event_date_idx on content.business_events (event_date);

-- ---------------------------------------------------------------------------
-- launch_windows: proposed / confirmed launch periods (section 8, step 2).
-- ---------------------------------------------------------------------------
create table content.launch_windows (
    id                 integer generated by default as identity primary key,
    start_date         date not null,
    end_date           date not null,
    business_event_id  integer references content.business_events (id) on delete set null,
    status             text not null default 'proposed',
    created_at         timestamptz not null default now(),
    constraint launch_windows_dates_chk check (end_date >= start_date),
    constraint launch_windows_status_chk check (status in ('proposed', 'confirmed'))
);

create index launch_windows_status_idx on content.launch_windows (status);
create index launch_windows_business_event_id_idx on content.launch_windows (business_event_id);

-- ---------------------------------------------------------------------------
-- data_gaps: periods with missing / unreliable data (section 6).
-- ---------------------------------------------------------------------------
create table content.data_gaps (
    id          integer generated by default as identity primary key,
    start_date  date not null,
    end_date    date not null,
    reason      text not null,
    created_at  timestamptz not null default now(),
    constraint data_gaps_dates_chk check (end_date >= start_date)
);

-- ---------------------------------------------------------------------------
-- content_posts: one row per Instagram post.
-- ---------------------------------------------------------------------------
create table content.content_posts (
    id                  uuid primary key default gen_random_uuid(),
    permalink           text not null unique,   -- normalised by code (strips /whatthemenopause/)
    shortcode           text not null,
    format              text not null,
    posted_at           timestamptz not null,
    caption             text,
    cta_keyword         text,
    is_partnership      boolean not null default false,
    is_boosted          boolean not null default false,
    duplicate_group_id  uuid,
    in_data_gap         boolean not null default false,
    stage_id            integer references content.account_stages (id),
    launch_window_id    integer references content.launch_windows (id) on delete set null,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    constraint content_posts_format_chk check (format in ('reel', 'carousel', 'image', 'story'))
);

create index content_posts_posted_at_idx on content.content_posts (posted_at);
create index content_posts_shortcode_idx on content.content_posts (shortcode);
create index content_posts_stage_id_idx on content.content_posts (stage_id);
create index content_posts_launch_window_id_idx on content.content_posts (launch_window_id);
create index content_posts_is_partnership_idx on content.content_posts (is_partnership);
create index content_posts_is_boosted_idx on content.content_posts (is_boosted);
create index content_posts_duplicate_group_id_idx on content.content_posts (duplicate_group_id)
    where duplicate_group_id is not null;

-- ---------------------------------------------------------------------------
-- content_metrics_snapshots: one row per post per pull. Every snapshot is kept.
-- ---------------------------------------------------------------------------
create table content.content_metrics_snapshots (
    id              bigint generated by default as identity primary key,
    post_id         uuid not null references content.content_posts (id) on delete cascade,
    captured_at     timestamptz not null,
    reach           bigint,          -- organic
    views           bigint,          -- organic
    saves           bigint,          -- organic
    shares          bigint,          -- organic
    comments        bigint,          -- organic
    likes           bigint,          -- organic
    view_rate       numeric,         -- reels only
    avg_watch_time  numeric,         -- reels only
    reach_paid      bigint,
    spend           numeric(12, 2),
    raw_json        jsonb not null,  -- full source row, for auditing
    constraint content_metrics_snapshots_post_captured_key unique (post_id, captured_at)
);

create index content_metrics_snapshots_captured_at_idx on content.content_metrics_snapshots (captured_at);

-- ---------------------------------------------------------------------------
-- content_tags: tagging results. Old taxonomy versions are kept.
-- ---------------------------------------------------------------------------
create table content.content_tags (
    id                 bigint generated by default as identity primary key,
    post_id            uuid not null references content.content_posts (id) on delete cascade,
    taxonomy_version   integer not null,
    content_type       text not null,
    topic              text not null,
    hook_type          text not null,
    other_description  text,          -- required when topic or hook_type is 'other' (section 5)
    confidence         text not null,
    tagged_by          text not null,
    tagged_at          timestamptz not null default now(),
    is_override        boolean not null default false,
    constraint content_tags_content_type_chk check (content_type in ('growth', 'authority', 'conversion')),
    constraint content_tags_confidence_chk check (confidence in ('high', 'medium', 'low')),
    constraint content_tags_tagged_by_chk check (tagged_by in ('llm', 'human')),
    constraint content_tags_other_description_chk check (
        (topic <> 'other' and hook_type <> 'other') or other_description is not null
    )
);

create index content_tags_post_version_idx on content.content_tags (post_id, taxonomy_version);
create index content_tags_content_type_idx on content.content_tags (content_type);
create index content_tags_topic_idx on content.content_tags (topic);
create index content_tags_hook_type_idx on content.content_tags (hook_type);

-- ---------------------------------------------------------------------------
-- analyst_runs: one row per Analyst run.
-- ---------------------------------------------------------------------------
create table content.analyst_runs (
    id            bigint generated by default as identity primary key,
    run_at        timestamptz not null default now(),
    settings      jsonb not null,    -- snapshot of analyst.config.yaml used
    report_links  jsonb,             -- e.g. {"account_history": "https://..."}
    data_checks   jsonb,             -- e.g. {"row_count_matches": "pass", ...}
    created_at    timestamptz not null default now()
);

create index analyst_runs_run_at_idx on content.analyst_runs (run_at);

-- ---------------------------------------------------------------------------
-- pattern_scores: grouped scores produced by a run.
-- ---------------------------------------------------------------------------
create table content.pattern_scores (
    id                   bigint generated by default as identity primary key,
    run_id               bigint not null references content.analyst_runs (id) on delete cascade,
    group_by             text not null,     -- what was grouped, e.g. 'topic'
    group_value          text not null,     -- e.g. 'nervous_system_mood'
    stage_id             integer references content.account_stages (id),
    post_count           integer not null,
    weighted_post_count  numeric not null,
    scores               jsonb not null,    -- one score per metric, e.g. {"reach": 1.4, "saves": 0.8}
    class                text,
    constraint pattern_scores_class_chk check (class in ('evergreen', 'faded', 'emerging', 'early_signal'))
);

create index pattern_scores_run_id_idx on content.pattern_scores (run_id);
create index pattern_scores_stage_id_idx on content.pattern_scores (stage_id);
create index pattern_scores_group_idx on content.pattern_scores (group_by, group_value);

-- ---------------------------------------------------------------------------
-- Access: RLS on with no policies, so anon / authenticated API roles get
-- nothing. The Analyst uses service_role (which bypasses RLS) or a direct
-- Postgres connection.
-- ---------------------------------------------------------------------------
alter table content.account_stages            enable row level security;
alter table content.business_events           enable row level security;
alter table content.launch_windows            enable row level security;
alter table content.data_gaps                 enable row level security;
alter table content.content_posts             enable row level security;
alter table content.content_metrics_snapshots enable row level security;
alter table content.content_tags              enable row level security;
alter table content.analyst_runs              enable row level security;
alter table content.pattern_scores            enable row level security;

grant usage on schema content to service_role;
grant all on all tables in schema content to service_role;
grant all on all sequences in schema content to service_role;
